version: '3.8'

services:
  vyuhaa-dataroom:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - dataroom-network

networks:
  dataroom-network:
    driver: bridge