// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzhjagwjxkjlhwmpysxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6aGphZ3dqeGtqbGh3bXB5c3hhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MDYxOTYsImV4cCI6MjA2ODA4MjE5Nn0.09Mn86dbMhNY7r3TmvObfdbjbhocjG9Qp9o3DzJTLk0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});